package com.vibecodingjapan.gymplayer.ui

import com.vibecodingjapan.gymplayer.AppLanguage

/** Localizes legacy Japanese UI strings while keeping user-provided content untouched. */
internal fun localizeUiText(text: String, language: AppLanguage): String {
  if (language == AppLanguage.JAPANESE || text.isBlank()) return text
  val replacements = translations.getValue(language)
  replacements[text]?.let { return it }
  var result = text
  replacements.entries.sortedByDescending { it.key.length }.forEach { (source, target) -> result = result.replace(source, target) }
  return result
}

private val translations =
  mapOf(
    AppLanguage.CHINESE to mapOf(
      "アカウントにログインして、データをクラウドに同期します。" to "登录账户并将数据同步到云端。",
      "アプリ起動時はネットワーク確認を行わず、ログアウトするまでローカル保存データで利用できます。" to "启动时不会检查网络；退出登录前可继续使用本地数据。",
      "マシン重量だけに適用します。利用者の体重は常に kg で保存・表示します。" to "仅用于器械重量。用户体重始终以 kg 保存和显示。",
      "MP3 / WAV / M4A など audio/* として見えるファイルを自動で読み込みます。" to "自动读取显示为 audio/* 的 MP3、WAV、M4A 等文件。",
      "ⓘ 体調がすぐれない場合は無理をせず、休憩を取りましょう。" to "ⓘ 如身体不适，请勿勉强并适当休息。",
      "安全にトレーニングを行うために数値を入力してください。" to "请输入数值以确保安全训练。",
      "✓ このセットを完了" to "✓ 完成本组",
      "▶ トレーニング開始" to "▶ 开始训练",
      "▶ スタート" to "▶ 开始",
      "▶ 再生" to "▶ 播放",
      "プレイリスト再生" to "播放列表",
      "音楽を楽しもう" to "享受音乐",
      "今日トレーニングするマシンを選択してください" to "请选择今天训练使用的器械",
      "お疲れ様でした。" to "辛苦了。",
      "セット完了しました。" to "组训练已完成。",
      "中断したトレーニングを復元しました" to "已恢复中断的训练",
      "今日のトレーニングを保存しました" to "已保存今天的训练",
      "今日のトレーニングメニュー" to "今日训练菜单",
      "トレーニング前の身体チェック" to "训练前身体检查",
      "今日選択したマシンだけを表示" to "仅显示今天选择的器械",
      "この日に運動記録はありません。" to "当天没有训练记录。",
      "修正する記録が見つかりません。" to "找不到要编辑的记录。",
      "追加できるマシンはありません。" to "没有可添加的器械。",
      "プレイリストに曲がありません" to "播放列表中没有歌曲",
      "プレイリストを削除しました" to "播放列表已删除",
      "プレイリストを再生中" to "正在播放列表",
      "同期しました。アップロードに成功しました。" to "同步完成，上传成功。",
      "オフラインです。ネットワークがありません。" to "当前离线，没有网络连接。",
      "休憩開始とセット完了の音声" to "休息开始与组训练完成语音",
      "今日のメニューを確認" to "查看今天的菜单",
      "トレーニングを記録" to "记录训练",
      "今日の身体数値" to "今日身体数据",
      "完了したトレーニング" to "已完成训练",
      "このマシンの履歴" to "该器械的历史",
      "この記録を修正" to "编辑此记录",
      "この記録を削除" to "删除此记录",
      "セット記録はありません。" to "没有组训练记录。",
      "クラウド同期" to "云端同步",
      "言語設定同期" to "语言设置同步",
      "未同期データ送信" to "上传未同步数据",
      "マシン情報取得" to "获取器械信息",
      "マシン画像取得" to "获取器械图片",
      "クラウド削除" to "删除云端数据",
      "ログイン確認" to "检查登录",
      "通信確認" to "检查网络",
      "同期を開始しました" to "同步已开始",
      "同期できませんでした" to "同步失败",
      "ログインできませんでした" to "登录失败",
      "プレイリスト再生" to "播放列表",
      "新しいプレイリスト" to "新播放列表",
      "フォルダを選択" to "选择文件夹",
      "音楽を楽しもう" to "享受音乐",
      "ログイン状態" to "登录状态",
      "ログイン済み" to "已登录",
      "未ログイン" to "未登录",
      "ログインしました" to "已登录",
      "ログアウトしました" to "已退出登录",
      "ログインしてください" to "请先登录",
      "処理中" to "处理中",
      "同期完了" to "同步完成",
      "同期失敗" to "同步失败",
      "同期する" to "同步",
      "同期" to "同步",
      "未同期" to "未同步",
      "最新" to "最新",
      "ホーム" to "首页",
      "ミュージック" to "音乐",
      "トレーニング詳細" to "训练详情",
      "トレーニング中" to "训练中",
      "トレーニング前" to "训练前",
      "トレーニング後" to "训练后",
      "トレーニング" to "训练",
      "プレイリスト" to "播放列表",
      "マシン番号" to "器械编号",
      "マシンを追加" to "添加器械",
      "セット記録" to "组训练记录",
      "合計セット数" to "总组数",
      "合計マシン数" to "器械总数",
      "完成状況" to "完成进度",
      "休憩に入ります" to "开始休息",
      "休憩終了アラーム" to "休息结束提醒",
      "休憩終了" to "休息结束",
      "休憩中" to "休息中",
      "休憩" to "休息",
      "履歴を更新しました" to "历史记录已更新",
      "履歴を修正" to "编辑历史",
      "履歴に戻る" to "返回历史",
      "履歴" to "历史",
      "ワークアウトを削除しました" to "训练已删除",
      "運動記録を削除しました" to "训练记录已删除",
      "曲順を保存しました" to "歌曲顺序已保存",
      "削除" to "删除",
      "修正" to "编辑",
      "キャンセル" to "取消",
      "閉じる" to "关闭",
      "保存" to "保存",
      "終了時間" to "结束时间",
      "開始時間" to "开始时间",
      "終了" to "结束",
      "開始" to "开始",
      "完了" to "完成",
      "失敗" to "失败",
      "現在" to "当前",
      "必須入力" to "必填",
      "メールアドレス" to "邮箱地址",
      "パスワード" to "密码",
      "ログアウト" to "退出登录",
      "ログイン" to "登录",
      "設定" to "设置",
      "表示言語" to "显示语言",
      "重量単位" to "重量单位",
      "重量" to "重量",
      "回数" to "次数",
      "最高血圧" to "收缩压",
      "最低血圧" to "舒张压",
      "血圧" to "血压",
      "心拍数" to "心率",
      "体脂肪率" to "体脂率",
      "筋肉量" to "肌肉量",
      "体水分率" to "体水分率",
      "基礎代謝量" to "基础代谢",
      "内臓脂肪" to "内脏脂肪",
      "体重" to "体重",
      "音量" to "音量",
      "選択日" to "选择日期",
      "選択" to "已选",
      "再生中" to "正在播放",
      "再生" to "播放",
      "セット目" to "组",
      "セット" to "组",
      "号機" to "号器械",
      "曲を読み込みました" to "首歌曲已导入",
      "曲" to "首",
      "件" to "条",
      "回" to "次",
      "秒" to "秒",
      "組" to "组",
      "年" to "年",
      "月" to "月",
      "火" to "二",
      "水" to "三",
      "木" to "四",
      "金" to "五",
      "土" to "六",
      "日" to "日",
    ),
    AppLanguage.ENGLISH to mapOf(
      "アカウントにログインして、データをクラウドに同期します。" to "Sign in to sync your data to the cloud.",
      "アプリ起動時はネットワーク確認を行わず、ログアウトするまでローカル保存データで利用できます。" to "The app uses local data without a startup network check until you sign out.",
      "マシン重量だけに適用します。利用者の体重は常に kg で保存・表示します。" to "Applies only to machine weights. Body weight is always stored and shown in kg.",
      "安全にトレーニングを行うために数値を入力してください。" to "Enter your readings to train safely.",
      "MP3 / WAV / M4A など audio/* として見えるファイルを自動で読み込みます。" to "Automatically imports MP3, WAV, M4A, and other files exposed as audio/*.",
      "ⓘ 体調がすぐれない場合は無理をせず、休憩を取りましょう。" to "ⓘ If you feel unwell, stop and take a rest.",
      "✓ このセットを完了" to "✓ Complete this set", "▶ トレーニング開始" to "▶ Start training", "▶ スタート" to "▶ Start", "▶ 再生" to "▶ Play",
      "プレイリスト再生" to "Play playlist", "音楽を楽しもう" to "Enjoy your music",
      "今日トレーニングするマシンを選択してください" to "Select the machines you will use today",
      "お疲れ様でした。" to "Great work. ", "セット完了しました。" to "sets completed.",
      "今日のトレーニングメニュー" to "Today's training menu", "トレーニング前の身体チェック" to "Pre-workout body check",
      "今日選択したマシンだけを表示" to "Showing only today's selected machines", "今日のトレーニングを保存しました" to "Today's workout was saved",
      "中断したトレーニングを復元しました" to "Interrupted workout restored", "この日に運動記録はありません。" to "No workout records for this day.",
      "修正する記録が見つかりません。" to "The record to edit was not found.", "追加できるマシンはありません。" to "No machines are available to add.",
      "同期しました。アップロードに成功しました。" to "Sync complete. Upload succeeded.", "オフラインです。ネットワークがありません。" to "You are offline. No network is available.",
      "休憩開始とセット完了の音声" to "Voice for rest start and set completion", "今日のメニューを確認" to "Review today's menu", "トレーニングを記録" to "Record your workout",
      "今日の身体数値" to "Today's body metrics", "完了したトレーニング" to "Completed workouts", "このマシンの履歴" to "Machine history",
      "この記録を修正" to "Edit this record", "この記録を削除" to "Delete this record", "セット記録はありません。" to "No set records.",
      "言語設定同期" to "Sync language setting", "未同期データ送信" to "Upload pending data", "マシン情報取得" to "Download machine data", "マシン画像取得" to "Download machine images",
      "クラウド削除" to "Delete cloud records", "ログイン確認" to "Check sign-in", "通信確認" to "Check connection", "同期を開始しました" to "Sync started",
      "同期できませんでした" to "Could not sync", "ログインできませんでした" to "Could not sign in", "プレイリストに曲がありません" to "The playlist has no tracks",
      "プレイリストを削除しました" to "Playlist deleted", "プレイリストを再生中" to "Playing playlist", "新しいプレイリスト" to "New playlist", "フォルダを選択" to "Choose folder",
      "ログイン状態" to "Sign-in status", "ログイン済み" to "Signed in", "未ログイン" to "Signed out", "ログインしました" to "Signed in", "ログアウトしました" to "Signed out", "ログインしてください" to "Please sign in",
      "処理中" to "Processing", "同期完了" to "Sync complete", "同期失敗" to "Sync failed", "同期する" to "Sync", "同期" to "Sync", "未同期" to "Not synced", "最新" to "Up to date",
      "ホーム" to "Home", "ミュージック" to "Music", "トレーニング詳細" to "Workout details", "トレーニング中" to "Training", "トレーニング前" to "Before workout", "トレーニング後" to "After workout", "トレーニング" to "Training",
      "プレイリスト" to "Playlists", "マシン番号" to "Machine number", "マシンを追加" to "Add machine", "セット記録" to "Set records", "合計セット数" to "Total sets", "合計マシン数" to "Total machines", "完成状況" to "Progress",
      "休憩に入ります" to "Rest starts now", "休憩終了アラーム" to "Rest-end alarm", "休憩終了" to "Rest finished", "休憩中" to "Resting", "休憩" to "Rest",
      "履歴を更新しました" to "History updated", "履歴を修正" to "Edit history", "履歴に戻る" to "Back to history", "履歴" to "History",
      "ワークアウトを削除しました" to "Workout deleted", "運動記録を削除しました" to "Workout record deleted", "曲順を保存しました" to "Track order saved",
      "削除" to "Delete", "修正" to "Edit", "キャンセル" to "Cancel", "閉じる" to "Close", "保存" to "Save", "終了時間" to "End time", "開始時間" to "Start time", "終了" to "Finish", "開始" to "Start", "完了" to "Complete", "失敗" to "Failed", "現在" to "Current", "必須入力" to "Required",
      "メールアドレス" to "Email", "パスワード" to "Password", "ログアウト" to "Sign out", "ログイン" to "Sign in", "設定" to "Settings", "重量単位" to "Weight unit", "重量" to "Weight", "回数" to "Reps",
      "表示言語" to "Display language",
      "最高血圧" to "Systolic", "最低血圧" to "Diastolic", "血圧" to "Blood pressure", "心拍数" to "Heart rate", "体脂肪率" to "Body fat", "筋肉量" to "Muscle mass", "体水分率" to "Body water", "基礎代謝量" to "Basal metabolism", "内臓脂肪" to "Visceral fat", "体重" to "Weight", "音量" to "Volume",
      "選択日" to "Selected date", "選択" to "Selected", "再生中" to "Playing", "再生" to "Play", "セット目" to "set", "セット" to "sets", "号機" to "Machine ", "曲を読み込みました" to " tracks imported", "曲" to " tracks", "件" to " records", "回" to " reps", "秒" to "sec", "組" to "sets",
      "月" to "Mon", "火" to "Tue", "水" to "Wed", "木" to "Thu", "金" to "Fri", "土" to "Sat", "日" to "Sun",
    ),
    AppLanguage.KOREAN to mapOf(
      "アカウントにログインして、データをクラウドに同期します。" to "계정에 로그인하여 데이터를 클라우드에 동기화합니다.",
      "アプリ起動時はネットワーク確認を行わず、ログアウトするまでローカル保存データで利用できます。" to "시작 시 네트워크를 확인하지 않으며 로그아웃 전까지 로컬 데이터를 사용합니다.",
      "マシン重量だけに適用します。利用者の体重は常に kg で保存・表示します。" to "머신 중량에만 적용됩니다. 체중은 항상 kg으로 저장·표시됩니다.",
      "安全にトレーニングを行うために数値を入力してください。" to "안전한 운동을 위해 수치를 입력하세요.", "今日トレーニングするマシンを選択してください" to "오늘 사용할 머신을 선택하세요",
      "MP3 / WAV / M4A など audio/* として見えるファイルを自動で読み込みます。" to "audio/*로 표시되는 MP3, WAV, M4A 등의 파일을 자동으로 불러옵니다.",
      "ⓘ 体調がすぐれない場合は無理をせず、休憩を取りましょう。" to "ⓘ 몸 상태가 좋지 않으면 무리하지 말고 쉬세요.",
      "✓ このセットを完了" to "✓ 이 세트 완료", "▶ トレーニング開始" to "▶ 운동 시작", "▶ スタート" to "▶ 시작", "▶ 再生" to "▶ 재생",
      "プレイリスト再生" to "플레이리스트 재생", "音楽を楽しもう" to "음악을 즐겨보세요",
      "お疲れ様でした。" to "수고하셨습니다. ", "セット完了しました。" to "세트를 완료했습니다.", "今日のトレーニングメニュー" to "오늘의 운동 메뉴", "トレーニング前の身体チェック" to "운동 전 신체 확인",
      "今日選択したマシンだけを表示" to "오늘 선택한 머신만 표시", "今日のトレーニングを保存しました" to "오늘의 운동을 저장했습니다", "中断したトレーニングを復元しました" to "중단된 운동을 복원했습니다",
      "この日に運動記録はありません。" to "이 날짜의 운동 기록이 없습니다.", "修正する記録が見つかりません。" to "수정할 기록을 찾을 수 없습니다.", "追加できるマシンはありません。" to "추가할 수 있는 머신이 없습니다.",
      "同期しました。アップロードに成功しました。" to "동기화 및 업로드가 완료되었습니다.", "オフラインです。ネットワークがありません。" to "오프라인입니다. 네트워크가 없습니다.", "休憩開始とセット完了の音声" to "휴식 시작 및 세트 완료 음성",
      "今日のメニューを確認" to "오늘의 메뉴 확인", "トレーニングを記録" to "운동 기록", "今日の身体数値" to "오늘의 신체 수치", "完了したトレーニング" to "완료된 운동", "このマシンの履歴" to "이 머신의 기록",
      "この記録を修正" to "이 기록 수정", "この記録を削除" to "이 기록 삭제", "セット記録はありません。" to "세트 기록이 없습니다.", "言語設定同期" to "언어 설정 동기화", "未同期データ送信" to "미동기화 데이터 전송",
      "マシン情報取得" to "머신 정보 받기", "マシン画像取得" to "머신 이미지 받기", "クラウド削除" to "클라우드 삭제", "ログイン確認" to "로그인 확인", "通信確認" to "통신 확인", "同期を開始しました" to "동기화를 시작했습니다",
      "同期できませんでした" to "동기화하지 못했습니다", "ログインできませんでした" to "로그인하지 못했습니다", "プレイリストに曲がありません" to "플레이리스트에 곡이 없습니다", "プレイリストを削除しました" to "플레이리스트를 삭제했습니다",
      "プレイリストを再生中" to "플레이리스트 재생 중", "新しいプレイリスト" to "새 플레이리스트", "フォルダを選択" to "폴더 선택", "ログイン状態" to "로그인 상태", "ログイン済み" to "로그인됨", "未ログイン" to "로그아웃됨",
      "ログインしました" to "로그인했습니다", "ログアウトしました" to "로그아웃했습니다", "ログインしてください" to "로그인하세요", "処理中" to "처리 중", "同期完了" to "동기화 완료", "同期失敗" to "동기화 실패", "同期する" to "동기화", "同期" to "동기화", "未同期" to "미동기화", "最新" to "최신",
      "ホーム" to "홈", "ミュージック" to "음악", "トレーニング詳細" to "운동 상세", "トレーニング中" to "운동 중", "トレーニング前" to "운동 전", "トレーニング後" to "운동 후", "トレーニング" to "운동", "プレイリスト" to "플레이리스트",
      "マシン番号" to "머신 번호", "マシンを追加" to "머신 추가", "セット記録" to "세트 기록", "合計セット数" to "총 세트", "合計マシン数" to "총 머신", "完成状況" to "진행 상황", "休憩に入ります" to "휴식을 시작합니다", "休憩終了アラーム" to "휴식 종료 알람", "休憩終了" to "휴식 종료", "休憩中" to "휴식 중", "休憩" to "휴식",
      "履歴を更新しました" to "기록을 업데이트했습니다", "履歴を修正" to "기록 수정", "履歴に戻る" to "기록으로 돌아가기", "履歴" to "기록", "ワークアウトを削除しました" to "운동을 삭제했습니다", "運動記録を削除しました" to "운동 기록을 삭제했습니다", "曲順を保存しました" to "곡 순서를 저장했습니다",
      "削除" to "삭제", "修正" to "수정", "キャンセル" to "취소", "閉じる" to "닫기", "保存" to "저장", "終了時間" to "종료 시간", "開始時間" to "시작 시간", "終了" to "종료", "開始" to "시작", "完了" to "완료", "失敗" to "실패", "現在" to "현재", "必須入力" to "필수",
      "メールアドレス" to "이메일", "パスワード" to "비밀번호", "ログアウト" to "로그아웃", "ログイン" to "로그인", "設定" to "설정", "重量単位" to "중량 단위", "重量" to "중량", "回数" to "횟수",
      "表示言語" to "표시 언어",
      "最高血圧" to "수축기 혈압", "最低血圧" to "이완기 혈압", "血圧" to "혈압", "心拍数" to "심박수", "体脂肪率" to "체지방률", "筋肉量" to "근육량", "体水分率" to "체수분률", "基礎代謝量" to "기초대사량", "内臓脂肪" to "내장 지방", "体重" to "체중", "音量" to "음량", "選択日" to "선택 날짜", "選択" to "선택",
      "再生中" to "재생 중", "再生" to "재생", "セット目" to "세트", "セット" to "세트", "号機" to "번 머신", "曲を読み込みました" to "곡을 불러왔습니다", "曲" to "곡", "件" to "건", "回" to "회", "秒" to "초", "組" to "세트",
      "月" to "월", "火" to "화", "水" to "수", "木" to "목", "金" to "금", "土" to "토", "日" to "일",
    ),
  )
